kabc-nginx:
    image: nginx:latest
    container_name: kabc-nginx
    ports:
        - 80:80
    volumes:
        - ".:/var/www/html:rw"
        - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
        - kabc-php
        - kabc-mysql
kabc-php:
    build: docker/php/
    container_name: kabc-php
    volumes:
        - ".:/var/www/html:rw"
    links:
        - kabc-mysql
kabc-mysql:
    image: mysql:latest
    container_name: kabc-mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=kabc
        - MYSQL_USER=kabc
        - MYSQL_PASSWORD=kabc
